# Generated by Django 3.1.2 on 2020-10-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=70)),
                ('last_name', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('country', models.CharField(default='', max_length=70)),
                ('city', models.CharField(default='', max_length=70)),
                ('job_title', models.CharField(default='', max_length=70)),
                ('company', models.CharField(default='', max_length=70)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
